version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: django-image
    container_name: django-container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on: 
      - db
  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
        MYSQL_DATABASE: 'django-mysql'
        MYSQL_USER: 'root'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'